services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=baskip'
      - 'MYSQL_PASSWORD=baskip'
      - 'MYSQL_ROOT_PASSWORD=baskip_root'
      - 'MYSQL_USER=baskip_user'
    ports:
      - '3306:3306'